-- substituted with flutter-tools

-- require'lspconfig'.dartls.setup{
--     cmd = { "dart", O.dart.sdk_path, "--lsp" },
--     on_attach = require'lsp'.common_on_attach,
--     init_options = {
--       closingLabels = true,
--       flutterOutline = true,
--       onlyAnalyzeProjectsWithOpenFiles = true,
--       outline = true,
--       suggestFromUnimportedLibraries = true,
--     },
-- }
